### ISSUE TITLE
how about the result?

### ISSUE THREAD

**Issue by Barnonewdm** [tegg89/SRCNN-Tensorflow#10]
I have downloaded your code, and run it directly. It went well. But the result prediction is not the same as your proposal.
![test_image](https://cloud.githubusercontent.com/assets/22175925/24198334/72b5b422-0f40-11e7-8fea-1ba9ce46ffa2.png)

**Comment by da0c** [comment]
Try to use stride 21 -
`python main.py --is_train False --stride 21`

**Comment by Barnonewdm** [comment]
Yep, the result is the test result with the stride 21 changed to False. So I mean the mix process is something wrong.

**Comment by da0c** [comment]
Maybe... I try to understand))) with stride 21 there is no squared effect. 
But the size of an image changed from 288 to 273. Looks like the image is a bit cropped.

**Comment by tegg89** [comment]
At training step, size of stride should be default 14, however use stride 21 when testing. Then the block artifacts would not be appeared. 
The reason of the cropped result is that the input image has to go through pre-processing.  Modify the input image with no remainder when scaling up and down (`modcrop`).

**Comment by da0c** [comment]
By the way, after training more than 20,000 epochs I still got PSNR value ~26 dB on Set5 pictures... what am I doing wrong?

**Comment by TTfrd** [comment]
![test_image](https://cloud.githubusercontent.com/assets/19527826/26557651/9509a7fc-44d5-11e7-84fb-ef6a8d6b0b49.png)
After downloading your codes,I used my Tensorflow in python3.5 with windows10. I had changed some code to make it running, and then I trained those images(about 100) in file'Train' with command ‘python main.py.’ ,because there were not checkpoint in files . After training, I tested it with command
'python main.py --is_train Flase --stride 21 ' and found this result named'test_image', which looked liked so bad as a reconstruction image. I wonder if the training images dataset are so small or I did something wrong with training code . And would you please put those checkpoints on this Github so that I could test some images and correct myself? Thank you!

**Comment by uestclx** [comment]
I find that the image quality will improve if we change the interpolation methode to bicubic interpolation (as suggested in the original paper).
That means changing the original code line 53&54 in utils.py to:
`h, w= label_.shape
input_ = scipy.misc.imresize(label_, (h/scale, w/scale), interp='bicubic')
input_ = scipy.misc.imresize(input_, (h, w), interp='bicubic')`
I didn't calculate the PSNR, but the result looks better.
@da0c @TTfrd

**Comment by ubenz55555** [comment]
Nice Job! but I have a couple of questions :
(1) The original author of SRCNN paper has said he trains with momentum=0.9，but I can't find the momentum in this code ，is something wrong with this code?
(2 )Besides，I train this code with ubuntu cpu-only，takes me about one day，it seems train too fast. This code's number of epochs is 10，but the paper author of SRCNN 's max iteration is 15000000. This is different with the SRCNN author's work，Did you made some arrange of it?
thank you!

**Comment by tegg89** [comment]
@ubenz55555 
I didn't apply momentum in this repository. You can adjust the numbers of iteration and epoch via options.

**Comment by uestclx** [comment]
@ubenz55555 Hi, did you get the same result as the paper does? Meaning the srcnn result is better than simple bicubic interpolation result? I've ran 1500 iterations (1500 * 10 epochs), but the generated image is still blur, and worse than the bicubic interpo image. I've been kinda struggling here for almost 2 weeks...

**Comment by Barnonewdm** [comment]
@ubenz55555 Hi, actually I have cited one other version code(https://github.com/Barnonewdm/SRCNN-keras). And in this version the result seems good.

**Comment by ubenz55555** [comment]
@uestclx   I don't have a gpu , I'm training it with my ubuntu virtual box cpu-only, without changing tegg89's code , I let it run and didn't  get a good result. The result image seems blur and looks worse than the bicubic image result.

**Comment by ubenz55555** [comment]
@Barnonewdm The keras version that you tag seems different with the paper's author architecture. Firstly, I had take a look at the main.py , It seems use the number of filters of the three conv layer is 128/64/1, but the paper's author use 64/32/1. Secondly, the keras version seems use adam for stochastic gradient descent ,  but the paper's author use momentum sgd.

**Comment by FIGHTFORGLO** [comment]
hello,@tegg89,I see you use the test picture is very high definition, but after the model after the picture clarity but reduced。why?

**Comment by chensteven** [comment]
@tegg89 Thank your sharing this code but there are some problems with the predicted image. First, the resolution of your predicted image is smaller than the paper's, second it is much blurrier as mentioned already. Anyone know what to do?

**Comment by 2017develper** [comment]
hello , thank you for this work it is very interessested 
i have this error 
utils.py", line 145, in input_setup
    sub_label = label_[x+padding:x+padding+config.label_size, y+padding:y+padding+config.label_size] # [21 x 21]
TypeError: slice indices must be integers or None or have an __index__ method


can you help me please

**Comment by Barnonewdm** [comment]
@2017develper U need to check the index type, whether it is integer type.

**Comment by 2017develper** [comment]
thank you , but how i can correct them , i don't find the index type

**Comment by liyuanye** [comment]
@2017develper i think your padding isn't integers, check your '/' and '//'.

**Comment by ZeusAlpha** [comment]
Can anyone help me. I tried to understand the code and then I wrote my own version of SRCNN. In my version, everything remains the same except for the fact that I am passing in the entire image. Even after 1000 epocs, I am getting blurred image. Can anyone explain what I need to rectify in order to correct this issue.

**Comment by divjotkaur** [comment]
How to extract trained weights and biases?

**Comment by PrathamSoni** [comment]
The trained model is saved in the checkpoints folder.

**Comment by divjotkaur** [comment]
Thank u so much sir for replying

Sir i want know that who can I store the obtained weights in the form of a
Excel file?

**Comment by PrathamSoni** [comment]
I'm not sure you might be able to save it as a different file type in some
manner.
