### ISSUE TITLE
how to testing and output image

### ISSUE THREAD

**Issue by xhsoldier** [tegg89/SRCNN-Tensorflow#11]
I have run the 
`python main.py ` and
`python main.py --is_train False --stride 21`

no error output, I am wondering how to input an image then generate a new clear image?

**Comment by tegg89** [comment]
@xhsoldier 
According to the [model.py#L115](https://github.com/tegg89/SRCNN-Tensorflow/blob/master/model.py#L115), result image should be saved at respective folder.
