### ISSUE TITLE
H5 File doesn't shuffle

### ISSUE THREAD

**Issue by Codersadis** [tegg89/SRCNN-Tensorflow#12]
when generating h5 files both in training and testing, the order of training samples still remains the order of extracting from images.
In conventional implementation of SRCNN's MATLAB code, they shuffled the training samples before training.

**Comment by Barnonewdm** [comment]
If u sample the points randomly, there is no more need to reshuffle when in composing .h5 file.

**Comment by Codersadis** [comment]
@Barnonewdm 
u r right. There are many solutions for this issue.
I just want to inform the original contributor and persons who will use this repo.

And I think this issue can be ignored since @tegg89 does not show up to a long time.
