### ISSUE TITLE
How to change which file is being tested??

### ISSUE THREAD

**Issue by PrathamSoni** [tegg89/SRCNN-Tensorflow#13]
I attempted to test on the image using the command in the readme. Although the results are poor, I was wondering how to change which file to be tested one. Such as, if I wanted to apply the SRCNN to an image of my choosing.
![orig](https://user-images.githubusercontent.com/20586632/30512859-700bdf28-9ac6-11e7-9013-ca984bd8d283.png)

**Comment by Macchu-Pichu** [comment]
I am also having this issue.

**Comment by PrathamSoni** [comment]
The error is is in line 155 of utils.py...

The program automatically picks the third picture in the folder selected.
