### ISSUE TITLE
 Apply image file with bicubic interpolation

### ISSUE THREAD

**Issue by kweisamx** [tegg89/SRCNN-Tensorflow#16]
May I ask why the two line is mean bicubic interpolation? Are there  any reference?
https://github.com/tegg89/SRCNN-Tensorflow/blob/master/utils.py#L53-L54
Thanks.

**Comment by PrathamSoni** [comment]
The listed lines use bicubic interpolation to scale down and back up. This generates a lower quality image for training.

**Comment by kweisamx** [comment]
Thanks, @PrathamSoni ,
so 
```
scipy.ndimage.interpolation.zoom
```
is mean ==bicubic== interpolation?
because I search the [ref](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.ndimage.interpolation.zoom.html)
that i can't find bicubic. Or this just simulate bicubic?
Thanks.

**Comment by PrathamSoni** [comment]
https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.ndimage.interpolation.zoom.html

it uses spline interpolation. The default order is 3 which means bicubic.

**Comment by kweisamx** [comment]
Hi @PrathamSoni ,Thanks for your answer
Close
