### ISSUE TITLE
I don't understand the meaning of this code

### ISSUE THREAD

**Issue by liuchongwei** [tegg89/SRCNN-Tensorflow#22]
I guess this code is to make the image blurred
input_ = scipy.ndimage.interpolation.zoom(label_, (1./scale), prefilter=False)
input_ = scipy.ndimage.interpolation.zoom(input_, (scale/1.), prefilter=False)

But after I code like this, I find the image(channel = 3) become darker than before. Are there any problems?
image = scipy.ndimage.interpolation.zoom(image, (1./scale, 1./scale, 1), prefilter=False)
image = scipy.ndimage.interpolation.zoom(image, (scale/1., scale/1., 1), prefilter=False)

**Comment by PrathamSoni** [comment]
We downscale and upscale to generate base LR image for training.

**Comment by matt-dong** [comment]
There should be no problems with it.
