### ISSUE TITLE
I get an error when inference, any idea? thanks

### ISSUE THREAD

**Issue by kitterive** [tegg89/SRCNN-Tensorflow#3]
guoxiujiang@kdc-imggroup:~/projects/SRCNN-Tensorflow-master$ python main.py --is_train False --stride 21
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
{'batch_size': 128,
 'c_dim': 1,
 'checkpoint_dir': 'checkpoint',
 'epoch': 10,
 'image_size': 33,
 'is_train': False,
 'label_size': 21,
 'learning_rate': 0.0001,
 'sample_dir': 'sample',
 'scale': 3,
 'stride': 21}
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.4.0-53-generic
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:140] kernel driver does not appear to be running on this host (kdc-imggroup): /proc/driver/nvidia/version does not exist
 [*] Reading checkpoints...
 [*] Load SUCCESS
Testing...
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 43, in main
    srcnn.train(FLAGS)
  File "/home/guoxiujiang/projects/SRCNN-Tensorflow-master/model.py", line 112, in train
    imsave(merge, os.path.join(os.getcwd(), config.sample_dir))
  File "/home/guoxiujiang/projects/SRCNN-Tensorflow-master/utils.py", line 191, in imsave
    return scipy.misc.imsave(path, image)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 195, in imsave
    im = toimage(arr, channel_axis=2)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 287, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
guoxiujiang@kdc-imggroup:~/projects/SRCNN-Tensorflow-master$

**Comment by kitterive** [comment]
`guoxiujiang@kdc-imggroup:~/projects/SRCNN-Tensorflow-master$ python main.py --is_train False --stride 21
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
{'batch_size': 128,
 'c_dim': 1,
 'checkpoint_dir': 'checkpoint',
 'epoch': 10,
 'image_size': 33,
 'is_train': False,
 'label_size': 21,
 'learning_rate': 0.0001,
 'sample_dir': 'sample',
 'scale': 3,
 'stride': 21}
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.4.0-53-generic
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:140] kernel driver does not appear to be running on this host (kdc-imggroup): /proc/driver/nvidia/version does not exist
 [*] Reading checkpoints...
 [*] Load SUCCESS
Testing...
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 43, in main
    srcnn.train(FLAGS)
  File "/home/guoxiujiang/projects/SRCNN-Tensorflow-master/model.py", line 112, in train
    imsave(merge, os.path.join(os.getcwd(), config.sample_dir))
  File "/home/guoxiujiang/projects/SRCNN-Tensorflow-master/utils.py", line 191, in imsave
    return scipy.misc.imsave(path, image)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 195, in imsave
    im = toimage(arr, channel_axis=2)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 287, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
guoxiujiang@kdc-imggroup:~/projects/SRCNN-Tensorflow-master$ `

**Comment by hezw2016** [comment]
I have got this error too, how do you solve this?
