### ISSUE TITLE
About result

### ISSUE THREAD

**Issue by joei1981** [tegg89/SRCNN-Tensorflow#6]
I used your command "python main.py --is_train False --stride 21" for testing, and found a file named "sample/test_image.png" was created. I wonder what is "test_image.png" ? It is a grey image with a low quality. Thus, I wonder is it just a low quality image that your make for testing SRCNN ? And then how can I use SRCNN to make a super resolution result ?

**Comment by tegg89** [comment]
@joei1981 Test image is the result of super-resolution. I think maybe you should add more training epoch. I put 15,000 epochs for training to get a reasonable super-resolved image. 
According to the paper, the object is super-resolve the bilinear interpolated image. So the quality of super-resolved image must be poorer than an original image.

**Comment by joei1981** [comment]
@tegg89 Yes, you are right. I should using 15,000 epochs for making a better training module. But I wonder the result is a grey image. Thus, I want to change some settings to get a better training module, like set epoch by 15000, image_size by 640, label_size by 626, and c_dim by 3. However, there are errors triggered by such changes. Therefore, I have several questions about your code:
(1) If I want to get color super-resolution results, should I change c_dim into 3 ? But it seems only changing c_dim into 3 cannot work.
(2) Because the images I want to process are basically 640*480, should I change image_size into 640 for training ? Also label_size should be changed correspondingly.

**Comment by tegg89** [comment]
@joei1981 I haven't tested with my own image. If that does not work, then maybe try to change the codes in utils file. I think I fixed the code working only as gray channel.
