### ISSUE TITLE
ValueError: 'arr' does not have a suitable array shape for any mode.

### ISSUE THREAD

**Issue by vinnitu** [tegg89/SRCNN-Tensorflow#8]
How to fix it?

```
$ python main.py --is_train False --stride 21
...
 [*] Load SUCCESS
Testing...
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 43, in main
    srcnn.train(FLAGS)
  File "/home/user/SRCNN-Tensorflow/model.py", line 115, in train
    imsave(image_path, result)
  File "/home/user/SRCNN-Tensorflow/utils.py", line 191, in imsave
    return scipy.misc.imsave(path, image)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 195, in imsave
    im = toimage(arr, channel_axis=2)
  File "/usr/local/lib/python2.7/dist-packages/scipy/misc/pilutil.py", line 287, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
```

**Comment by xiaoshidai** [comment]
I have the same problem with you, did you solve this problem?

**Comment by xiaoshidai** [comment]
I found some people have the same problem and you had update your code, but the problem still exist. Did you test it again?

**Comment by xiaoshidai** [comment]
There a wrong in the code "util.py"
"""
def imsave(image, path):
  return scipy.misc.imsave(path, image)
"""
should be 
"""
def imsave(image, path):
  return scipy.misc.imsave(image,path)
"""

**Comment by tegg89** [comment]
@xiaoshidai @vinnitu Sorry for late reply. Because my machine is currently power-off, I cannot check it right now. I will make it right as soon as possible. Thanks

**Comment by xiaoshidai** [comment]
Did find that the super-resolution image is smaller than the original image, but the code in caffe does not have this problem? Did you have some idea about it?

**Comment by tegg89** [comment]
@xiaoshidai The size of super-resolved image and that of original image have to be different, because height size and width size of original image were changed due to do proper mod operation.

@vinnitu @xiaoshidai I fixed the problem. Now the result image should be saved.

**Comment by HCShi** [comment]
@xiaoshidai I also meet this problem ,and I modify the error as you said in util.py  , but it doesn't work . So could it be the quality of image or the quantity of the images?

**Comment by kjaisinghyadav** [comment]
@vinnitu @xiaoshidai   What need to be change to fix this probleam??

**Comment by ParmpalSinghGill** [comment]
check the shape of image before saving
